"""Add agreements, disclosures, compliance, and audit log tables

Revision autogenerated for feature patch.
"""
from alembic import op
import sqlalchemy as sa

revision = "20260626_add_agreements_compliance"
down_revision = "f6a7e0a01f06"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'agreements',
        sa.Column('agreement_id', sa.String(length=64), primary_key=True),
        sa.Column('agreement_type', sa.String(length=64), nullable=False),
        sa.Column('version', sa.String(length=32), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'agreement_acceptances',
        sa.Column('acceptance_id', sa.String(length=64), primary_key=True),
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('agreement_id', sa.String(length=64), nullable=False),
        sa.Column('agreement_type', sa.String(length=64), nullable=False),
        sa.Column('agreement_version', sa.String(length=32), nullable=False),
        sa.Column('accepted', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('ip_address', sa.String(length=128), nullable=True),
        sa.Column('device_info', sa.Text(), nullable=True),
        sa.Column('signature', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'electronic_signatures',
        sa.Column('signature_id', sa.String(length=64), primary_key=True),
        sa.Column('acceptance_id', sa.String(length=64), nullable=False),
        sa.Column('typed_name', sa.String(length=255), nullable=False),
        sa.Column('consent_checkbox', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('ip_address', sa.String(length=128), nullable=True),
        sa.Column('device_fingerprint', sa.String(length=256), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'criminal_disclosures',
        sa.Column('disclosure_id', sa.String(length=64), primary_key=True),
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('has_conviction', sa.Boolean(), nullable=False),
        sa.Column('offense_type', sa.String(length=255), nullable=True),
        sa.Column('severity', sa.String(length=32), nullable=True),
        sa.Column('conviction_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('state', sa.String(length=64), nullable=True),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.Column('rehabilitation', sa.Text(), nullable=True),
        sa.Column('attachments', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'compliance_reviews',
        sa.Column('review_id', sa.String(length=64), primary_key=True),
        sa.Column('user_id', sa.String(length=64), nullable=True),
        sa.Column('disclosure_id', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('assigned_to', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'investigations',
        sa.Column('investigation_id', sa.String(length=64), primary_key=True),
        sa.Column('user_id', sa.String(length=64), nullable=True),
        sa.Column('type', sa.String(length=64), nullable=False),
        sa.Column('evidence', sa.JSON(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('outcome', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        'audit_logs',
        sa.Column('log_id', sa.String(length=64), primary_key=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('user_id', sa.String(length=64), nullable=True),
        sa.Column('actor_id', sa.String(length=64), nullable=True),
        sa.Column('action_type', sa.String(length=128), nullable=False),
        sa.Column('before_state', sa.JSON(), nullable=True),
        sa.Column('after_state', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table('audit_logs')
    op.drop_table('investigations')
    op.drop_table('compliance_reviews')
    op.drop_table('criminal_disclosures')
    op.drop_table('electronic_signatures')
    op.drop_table('agreement_acceptances')
    op.drop_table('agreements')
